"""empty message

Revision ID: ad324b4500ad
Revises: aa41912b0123
Create Date: 2017-03-08 16:54:07.467529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad324b4500ad'
down_revision = 'aa41912b0123'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('userid', sa.Integer(), nullable=False))
    op.drop_constraint(u'user_profile_gender_key', 'user_profile', type_='unique')
    op.drop_column('user_profile', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('id', sa.INTEGER(), nullable=False))
    op.create_unique_constraint(u'user_profile_gender_key', 'user_profile', ['gender'])
    op.drop_column('user_profile', 'userid')
    # ### end Alembic commands ###
